/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.ris.src;

import app.ris.bo.Constants;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Container;
import java.awt.Dimension;
import java.io.File;
import javax.swing.JPanel;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *

 */
public class paneFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form paneFrame
     */
    
    public paneFrame() {
        initComponents();
        JPanel p1=new JPanel();
        JPanel p3=new JPanel();
        JPanel p2=new JPanel();
        JPanel p4=new JPanel();
        
        
        
//        JPanel buttonPanel = new JPanel();
//        JPanel buttonPanel1 = new JPanel();
//        buttonPanel.setPreferredSize(new Dimension(130,120));
//        buttonPanel.setLayout(new BorderLayout());
//        buttonPanel1.setPreferredSize(new Dimension(130,120));
//        buttonPanel1.setLayout(new BorderLayout());
//        btnReg.setPreferredSize(new Dimension(100, 100));
//        buttonPanel.add(jButton10,BorderLayout.NORTH);
//        buttonPanel.add(lblReg,BorderLayout.SOUTH);
//        buttonPanel1.add(btnReg,BorderLayout.NORTH);
//        buttonPanel1.add(lblReg,BorderLayout.SOUTH);
        
        Container pane=this.getContentPane();
        pane.setLayout(new BorderLayout());
        
//        panel1 = new JPanel(new FlowLayout());
        
        p1.setPreferredSize(new Dimension(200,200));
        p2.setPreferredSize(new Dimension(100,70));
        p3.setPreferredSize(new Dimension(200,200));
        p4.setPreferredSize(new Dimension(100,70));
        panel1.setPreferredSize(new Dimension(50,50));
        p1.setBackground(new Color(0,0,0,0));
        p2.setBackground(new Color(0,0,0,0));
        p3.setBackground(new Color(0,0,0,0));
        p4.setBackground(new Color(0,0,0,0));
        pane.setBackground(new Color(0,0,0,0));
        
//        panel1.add(buttonPanel,FlowLayout.LEFT);
//        panel1.add(buttonPanel1,FlowLayout.LEFT);
//        panel1.add(buttonPanel,FlowLayout.LEFT);
//        panel1.add(buttonPanel,FlowLayout.LEFT);
//        panel1.add(buttonPanel,FlowLayout.LEFT);
        
        pane.add(p1,BorderLayout.EAST);
        pane.add(p2,BorderLayout.SOUTH);
        pane.add(panel1,BorderLayout.CENTER);
        pane.add(p4,BorderLayout.NORTH);
        pane.add(p3,BorderLayout.WEST);
        this.pack();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        setRoleWiseMenus();
//        this.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        panel1 = new javax.swing.JPanel();
        btnReg = new javax.swing.JButton();
        lblReg = new javax.swing.JLabel();
        btnCounter = new javax.swing.JButton();
        lblCounter = new javax.swing.JLabel();
        btnTech = new javax.swing.JButton();
        lblTech = new javax.swing.JLabel();
        btnRep = new javax.swing.JButton();
        lblRep = new javax.swing.JLabel();
        lblAdd = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        empReg = new javax.swing.JButton();
        lblEmp = new javax.swing.JLabel();
        btnOrder = new javax.swing.JButton();
        lblOrder = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        btnTemp = new javax.swing.JButton();
        lblTemp = new javax.swing.JLabel();

        setMaximizable(true);
        setResizable(true);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        mainPanel.setBackground(new java.awt.Color(204, 204, 204));

        panel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Main Menu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 14))); // NOI18N

        btnReg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/ris/resources/Actions-document-edit-icon.png"))); // NOI18N
        btnReg.setIconTextGap(0);
        btnReg.setMargin(new java.awt.Insets(4, 4, 4, 4));
        btnReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegActionPerformed(evt);
            }
        });

        lblReg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblReg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReg.setText("Patient Registration");

        btnCounter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/ris/resources/Transport-Under-Computer-icon.png"))); // NOI18N
        btnCounter.setIconTextGap(0);
        btnCounter.setMargin(new java.awt.Insets(4, 4, 4, 4));
        btnCounter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCounterActionPerformed(evt);
            }
        });

        lblCounter.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCounter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCounter.setText("Counter Acknowledge");

        btnTech.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/ris/resources/machine.png"))); // NOI18N
        btnTech.setIconTextGap(0);
        btnTech.setMargin(new java.awt.Insets(4, 4, 4, 4));
        btnTech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTechActionPerformed(evt);
            }
        });

        lblTech.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTech.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTech.setText("Tech Acknowledge");

        btnRep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/ris/resources/xray.png"))); // NOI18N
        btnRep.setIconTextGap(0);
        btnRep.setMargin(new java.awt.Insets(4, 4, 4, 4));
        btnRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepActionPerformed(evt);
            }
        });

        lblRep.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblRep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRep.setText("Pending Results");

        lblAdd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAdd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAdd.setText("Addendum");

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/ris/resources/purchase-order.png"))); // NOI18N
        btnAdd.setIconTextGap(0);
        btnAdd.setMargin(new java.awt.Insets(4, 4, 4, 4));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        empReg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/ris/resources/employee.png"))); // NOI18N
        empReg.setIconTextGap(0);
        empReg.setMargin(new java.awt.Insets(4, 4, 4, 4));
        empReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empRegActionPerformed(evt);
            }
        });

        lblEmp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEmp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmp.setText("Staff Registration");

        btnOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/ris/resources/favicon-96x96.png"))); // NOI18N
        btnOrder.setIconTextGap(0);
        btnOrder.setMargin(new java.awt.Insets(4, 4, 4, 4));
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });

        lblOrder.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblOrder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOrder.setText("OrderEntry");

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/ris/resources/scan.png"))); // NOI18N
        jButton9.setIconTextGap(0);
        jButton9.setMargin(new java.awt.Insets(4, 4, 4, 4));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Reporting");

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/ris/resources/password.png"))); // NOI18N
        jButton10.setIconTextGap(0);
        jButton10.setMargin(new java.awt.Insets(4, 4, 4, 4));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Change Password");

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/ris/resources/exit.png"))); // NOI18N
        jButton11.setIconTextGap(0);
        jButton11.setMargin(new java.awt.Insets(4, 4, 4, 4));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Exit");

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/ris/resources/folder-icon.png"))); // NOI18N
        jButton12.setIconTextGap(0);
        jButton12.setMargin(new java.awt.Insets(4, 4, 4, 4));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("DICOM Directory");

        btnTemp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/ris/resources/temp.png"))); // NOI18N
        btnTemp.setIconTextGap(0);
        btnTemp.setMargin(new java.awt.Insets(4, 4, 4, 4));
        btnTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTempActionPerformed(evt);
            }
        });

        lblTemp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTemp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTemp.setText("Report Templates");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(btnReg))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panel1Layout.createSequentialGroup()
                                            .addGap(42, 42, 42)
                                            .addComponent(empReg)
                                            .addGap(7, 7, 7))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                                            .addGap(33, 33, 33)
                                            .addComponent(lblReg)))
                                    .addGroup(panel1Layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(lblEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(61, 61, 61)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnTemp))
                                    .addComponent(lblTemp))))
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel1Layout.createSequentialGroup()
                                        .addGap(90, 90, 90)
                                        .addComponent(btnCounter)
                                        .addGap(27, 27, 27))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblCounter)
                                        .addGap(15, 15, 15)))
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel1Layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(btnTech))
                                    .addGroup(panel1Layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addComponent(lblTech, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnRep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblRep, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(73, 73, 73)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(633, 633, 633)))
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton10)
                            .addComponent(jButton9)))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton11))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(btnTech)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTech))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnReg)
                            .addComponent(btnCounter))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblReg))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(btnOrder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCounter)
                            .addComponent(lblOrder)))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(empReg)
                            .addComponent(btnTemp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTemp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblAdd))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(btnRep)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblRep))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jButton10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton11)
                    .addComponent(jButton12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addContainerGap())
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap(254, Short.MAX_VALUE)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        BackgroundPanel bp = new BackgroundPanel("C:\\Users\\Public\\Pictures\\Sample Pictures\\Desert.jpg",this);
            mainPanel.add(bp);
            mainPanel.validate();
            mainPanel.repaint();
            
    }//GEN-LAST:event_formFocusGained

    private void btnRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegActionPerformed
//        if(Constants.obj!=null)
//        {
//            Constants.obj.dispose();
//        }
//        try {
//            Constants.bgFrame.hide();
//            try {
//                if (Constants.webcam != null || Constants.webcam.open()) {
//                    Constants.webcam.close();
//                }
//            } catch (Exception e) {
//            }
//
//            PatientRegistration r = new PatientRegistration();
//
//            BasicInternalFrameUI ui = (BasicInternalFrameUI) r.getUI();
//            Container north = (Container) ui.getNorthPane();
//            north.remove(0);
//            north.validate();
//            north.repaint();
//            Constants.pane1.add(r);
//            Constants.obj=r;
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
    }//GEN-LAST:event_btnRegActionPerformed

    private void btnCounterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCounterActionPerformed
        if(Constants.obj!=null)
        {
            Constants.obj.dispose();
        }
        try {
            Constants.bgFrame.hide();
            try {
                if (Constants.webcam != null || Constants.webcam.open()) {
                    Constants.webcam.close();
                }
            } catch (Exception e) {
            }
            CounterAck reg = new CounterAck();

            BasicInternalFrameUI ui = (BasicInternalFrameUI) reg.getUI();
            Container north = (Container) ui.getNorthPane();
            north.remove(0);
            north.validate();
            north.repaint();
            Constants.pane1.add(reg);
            Constants.obj = reg;
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnCounterActionPerformed

    private void btnTechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTechActionPerformed
        if(Constants.obj!=null)
        {
            Constants.obj.dispose();
        }
        try{
            Constants.bgFrame.hide();
            try {
                if (Constants.webcam != null || Constants.webcam.open()) {
                    Constants.webcam.close();
                }
            } catch (Exception e) {
            }
            TechAcknowledge reg = new TechAcknowledge();

            BasicInternalFrameUI ui = (BasicInternalFrameUI) reg.getUI();
            Container north = (Container) ui.getNorthPane();
            north.remove(0);
            north.validate();
            north.repaint();
            Constants.pane1.add(reg);
            Constants.obj=reg;
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnTechActionPerformed

    private void btnRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepActionPerformed
        if(Constants.obj!=null)
        {
            Constants.obj.dispose();
        }
        try {
            Constants.bgFrame.hide();
            try {
                if (Constants.webcam != null || Constants.webcam.open()) {
                    Constants.webcam.close();
                }
            } catch (Exception e) {
            }
            DoctorReporting r = new DoctorReporting();

            BasicInternalFrameUI ui = (BasicInternalFrameUI) r.getUI();
            Container north = (Container) ui.getNorthPane();
            north.remove(0);
            north.validate();
            north.repaint();
            Constants.pane1.add(r);
            Constants.obj=r;
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnRepActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if(Constants.obj!=null)
        {
            Constants.obj.dispose();
        }
        try {
            Constants.bgFrame.hide();
            try {
                if (Constants.webcam != null || Constants.webcam.open()) {
                    Constants.webcam.close();
                }
            } catch (Exception e) {
            }
            ReportAdendum reg = new ReportAdendum();

            BasicInternalFrameUI ui = (BasicInternalFrameUI) reg.getUI();
            Container north = (Container) ui.getNorthPane();
            north.remove(0);
            north.validate();
            north.repaint();
            Constants.pane1.add(reg);
            Constants.obj=reg;
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void empRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empRegActionPerformed
        if(Constants.obj!=null)
        {
            Constants.obj.dispose();
        }
        try {
            Constants.bgFrame.hide();
            try {
                if (Constants.webcam != null || Constants.webcam.open()) {
                    Constants.webcam.close();
                }
            } catch (Exception e) {
            }
            EmployeeRegistration r = new EmployeeRegistration();

            BasicInternalFrameUI ui = (BasicInternalFrameUI) r.getUI();
            Container north = (Container) ui.getNorthPane();
            north.remove(0);
            north.validate();
            north.repaint();
            Constants.pane1.add(r);
            Constants.obj=r;
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_empRegActionPerformed

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
//        if(Constants.obj!=null)
//        {
//            Constants.obj.dispose();
//        }
//        try {
//            Constants.bgFrame.hide();
//            try {
//                if (Constants.webcam != null || Constants.webcam.open()) {
//                    Constants.webcam.close();
//                }
//            } catch (Exception e) {
//            }
//            OrderEntry reg = new OrderEntry();
//
//            BasicInternalFrameUI ui = (BasicInternalFrameUI) reg.getUI();
//            Container north = (Container) ui.getNorthPane();
//            north.remove(0);
//            north.validate();
//            north.repaint();
//            Constants.pane1.add(reg);
//            Constants.obj=reg;
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
    }//GEN-LAST:event_btnOrderActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if(Constants.obj!=null)
        {
            Constants.obj.dispose();
        }
        try {
            Constants.bgFrame.hide();
            try {
                if (Constants.webcam != null || Constants.webcam.open()) {
                    Constants.webcam.close();
                }
            } catch (Exception e) {
            }
            ReportPrinting reg = new ReportPrinting();

            BasicInternalFrameUI ui = (BasicInternalFrameUI) reg.getUI();
            Container north = (Container) ui.getNorthPane();
            north.remove(0);
            north.validate();
            north.repaint();
            Constants.pane1.add(reg);
            Constants.obj=reg;
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        if(Constants.obj!=null)
        {
            Constants.obj.dispose();
        }
        try {
            Constants.bgFrame.hide();
            try {
                if (Constants.webcam != null || Constants.webcam.open()) {
                    Constants.webcam.close();
                }
            } catch (Exception e) {
            }
            ChangePassword reg = new ChangePassword();

            BasicInternalFrameUI ui = (BasicInternalFrameUI) reg.getUI();
            Container north = (Container) ui.getNorthPane();
            north.remove(0);
            north.validate();
            north.repaint();
            Constants.pane1.add(reg);
            Constants.obj=reg;
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        try {
            if (Constants.webcam != null || Constants.webcam.open()) {
                Constants.webcam.close();
            }
        } catch (Exception e) {
        }
        dispose();
        System.exit(0);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        if(Constants.obj!=null)
        {
            Constants.obj.dispose();
        }
        try {
            Constants.bgFrame.hide();
            try {
                if (Constants.webcam != null || Constants.webcam.open()) {
                    Constants.webcam.close();
                }
            } catch (Exception e) {
            }
            DicomDirectory reg = new DicomDirectory();

            BasicInternalFrameUI ui = (BasicInternalFrameUI) reg.getUI();
            Container north = (Container) ui.getNorthPane();
            north.remove(0);
            north.validate();
            north.repaint();
            Constants.pane1.add(reg);
            Constants.obj = reg;
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void btnTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTempActionPerformed
        if(Constants.obj!=null)
        {
            Constants.obj.dispose();
        }
        try {
            Constants.bgFrame.hide();
            try {
                if (Constants.webcam != null || Constants.webcam.open()) {
                    Constants.webcam.close();
                }
            } catch (Exception e) {
            }
            Template r = new Template();

            BasicInternalFrameUI ui = (BasicInternalFrameUI) r.getUI();
            Container north = (Container) ui.getNorthPane();
            north.remove(0);
            north.validate();
            north.repaint();
            Constants.pane1.add(r);
            Constants.obj=r;
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnTempActionPerformed

    
    public class BackgroundPanel extends javax.swing.JPanel {

        java.awt.Image image;
        paneFrame pf=null;
        public BackgroundPanel(String path,paneFrame p) {
            try {
                pf=p;
                image = javax.imageio.ImageIO.read(new File(path));
                java.awt.Dimension size = new java.awt.Dimension(pf.mainPanel.getSize());
                setPreferredSize(size);
                setMinimumSize(size);
                setMaximumSize(size);
                setSize(size);
                setLayout(null);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

        @Override
        protected void paintComponent(java.awt.Graphics g) {
            super.paintComponent(g);
            if (image != null) {
                g.drawImage(image, 0, 0, this.getWidth(), this.getHeight(), this);
            }
        }
    }
    
    private void setRoleWiseMenus() {
        switch (Constants.employeeRole) {
            case "R":
//                template.setVisible(false);
//                cpt.setVisible(false);
//                price.setVisible(false);
                empReg.setEnabled(false);
                lblEmp.setEnabled(false);
                btnRep.setEnabled(false);
                lblRep.setEnabled(false);
                btnTech.setEnabled(false);
                lblTech.setEnabled(false);
                btnAdd.setEnabled(false);
                lblAdd.setEnabled(false);
                btnTemp.setEnabled(false);
                lblTemp.setEnabled(false);
                break;

            case "T":
//                template.setVisible(false);
//                cpt.setVisible(false);
//                price.setVisible(false);
                btnRep.setEnabled(false);
                lblRep.setEnabled(false);
                empReg.setEnabled(false);
                lblEmp.setEnabled(false);
                btnAdd.setEnabled(false);
                lblAdd.setEnabled(false);
                btnTemp.setEnabled(false);
                lblTemp.setEnabled(false);
                break;
            case "D":
//                reg.setVisible(false);
//                cpt.setVisible(false);
//                price.setVisible(false);

                empReg.setEnabled(false);
                lblEmp.setEnabled(false);
                btnOrder.setEnabled(false);
                lblOrder.setEnabled(false);
                btnReg.setEnabled(false);
                lblReg.setEnabled(false);
                
                btnCounter.setEnabled(false);
                lblCounter.setEnabled(false);
                btnTech.setEnabled(false);
                lblTech.setEnabled(false);
//                tech.setVisible(false);
//                coun.setVisible(false);
//                pic.setVisible(false);
                break;
            case "A":
            default:
                break;
        }
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCounter;
    private javax.swing.JButton btnOrder;
    private javax.swing.JButton btnReg;
    private javax.swing.JButton btnRep;
    private javax.swing.JButton btnTech;
    private javax.swing.JButton btnTemp;
    private javax.swing.JButton empReg;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblAdd;
    private javax.swing.JLabel lblCounter;
    private javax.swing.JLabel lblEmp;
    private javax.swing.JLabel lblOrder;
    private javax.swing.JLabel lblReg;
    private javax.swing.JLabel lblRep;
    private javax.swing.JLabel lblTech;
    private javax.swing.JLabel lblTemp;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panel1;
    // End of variables declaration//GEN-END:variables
}
